// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmjmlqmwfarqlrhrkyla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtam1scW13ZmFycWxyaHJreWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NDQ1NjAsImV4cCI6MjA3NjAyMDU2MH0.fGVOrhe1B2GlQY9pNRqi42T21wmlkZtV1iihqBc0QDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});